### ISSUE TITLE
Training transformer - Missing file

### ISSUE THREAD

**Issue by additya1998** [wywu/ReenactGAN#4]
The script for training the transformer uses a 'sample_40000.txt' file, which is not present in the CelebV dataset. Can you please explain what the file contains and the data format in the file?

**Comment by liren2515** [comment]
> The script for training the transformer uses a 'sample_40000.txt' file, which is not present in the CelebV dataset. Can you please explain what the file contains and the data format in the file?

The script for training the transformer now is corrected. What it needs here is "all_98pt.txt', just as what you use to train the decoder.

**Comment by additya1998** [comment]
Thanks. Also, is there a way I can generate a similar file for a new set of images (not part of the CelebV dataset) ?

**Comment by liren2515** [comment]
> Thanks. Also, is there a way I can generate a similar file for a new set of images (not part of the CelebV dataset) ?

Yes. Actually we don't need the landmarks for both the training of the Decoder and the Transformer. When we read 'all_98pt.txt', what we use is just the image name shown at the end of each line. So you can create a txt file which containing the name list of images. (Maybe you need to make some small modifications to our dataloader as well, but it is easy to implement.)

**Comment by additya1998** [comment]
Thanks, works now.

**Comment by ghost** [comment]
Could you please describe how you trained it on another dataset. How did you generate the text file containing the image names.
