### ISSUE TITLE
sample_40000.txt not found

### ISSUE THREAD

**Issue by MasterXiYu** [wywu/ReenactGAN#7]

**Comment by MasterXiYu** [comment]
Thanks for release code, but I found that it can not find './CelebV/Donald_Trump/sample_40000.txt', I have download CelebV from Google Drive， but when I run train_transformer, it does not work.
Did I miss something?
Many Thanks

**Comment by MasterXiYu** [comment]
So  I try to rename sample_40000.txt as all_98pt.txt........

**Comment by liren2515** [comment]
> So  I try to rename sample_40000.txt as all_98pt.txt........

Yes, just rename it. It's a small typo.

**Comment by MasterXiYu** [comment]
> > So  I try to rename sample_40000.txt as all_98pt.txt........
> 
> Yes, just rename it. It's a small typo.

thanks a lot
